### ISSUE TITLE
performance without pretraining

### ISSUE THREAD

**Issue by liuzh2016** [TencentAILabHealthcare/scBERT#17]
I did a ablation study whether pretraining could benefit downstream tasks by finetuning without loading state dict from checkpoint. All other settings were kept same. the finetuning process stopped at epoch 34. All reported metrics are comparable to the paper results. Metrics for some rare cell types and overall are even better. 
How to prove the pretraining benefit?

**Comment by brigmecham** [comment]
Did you ever figure this out?

**Comment by TencentAILabHealthcare** [comment]
Model pre-training was originally designed to improve the generalizability of the model, making it applicable for diverse downstream tasks and robust to data from multiple centers. Narrowing down to single task on single dataset could not prove the model's generalizability. The model performs well on different tasks and is robust to the batch effect when training on one dataset and then evaluating on another dataset. The cross-organ experiment in the original paper demonstrates the efficiency of the design.
