### ISSUE TITLE
labels for zheng68K dataset

### ISSUE THREAD

**Issue by zhaoli2017** [TencentAILabHealthcare/scBERT#2]
Hi,

Would you mind sharing the cell label file for the Zheng68K dataset mentioned in your paper? I found one, but seems it's inconsistent with the statistics reported in your paper.
https://github.com/theislab/scanpy_usage/blob/38030605c74c755167302caa431cf3ff62de646f/170503_zheng17/data/zheng17_bulk_lables.txt

Thanks a lot!
Zhao

**Comment by TencentAILabHealthcare** [comment]
Hi Zhao,
