### ISSUE TITLE
error with finetune.py

### ISSUE THREAD

**Issue by pchiang5** [TencentAILabHealthcare/scBERT#22]
Hello,

Thank you for providing the tool.

However, I encountered an error with `python -m torch.distributed.launch finetune.py`:
The input h5ad file has been processed with your preprocess.py without errors.

> /usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
> and will be removed in future. Use torchrun.
> Note that --use_env is set by default in torchrun.
> If your script expects `--local_rank` argument to be set, please
> change it to read from `os.environ['LOCAL_RANK']` instead. See 
> https://pytorch.org/docs/stable/distributed.html#launch-utility for 
> further instructions
> 
>   warnings.warn(
> /content/performer_pytorch.py:115: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
> The boolean parameter 'some' has been replaced with a string parameter 'mode'.
> Q, R = torch.qr(A, some)
> should be replaced with
> Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2349.)
>   q, r = torch.qr(unstructured_block.cpu(), some = True)
>     ==  Epoch: 1 | Training Loss: 3.652004 | Accuracy: 0.7500%  ==
>     ==  Epoch: 1 | Validation Loss: 3.654254 | F1 Score: 0.000274  ==
> [[0 0 0 ... 0 0 0]
>  [0 0 0 ... 0 0 0]
>  [0 0 0 ... 0 0 0]
>  ...
>  [0 0 0 ... 0 0 0]
>  [0 0 0 ... 0 0 0]
>  [0 0 0 ... 0 0 0]]
> Traceback (most recent call last):
>   File "finetune.py", line 262, in <module>
>     print(classification_report(truths, predictions, target_names=label_dict.tolist(), digits=4))
>   File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py", line 2132, in classification_report
>     raise ValueError(
> ValueError: Number of classes, 37, does not match size of target_names, 38. Try specifying the labels parameter
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25554) of binary: /usr/bin/python3
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
>     main()
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
>     launch(args)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
>     run(args)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
>     elastic_launch(
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> finetune.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-01-09_08:36:05
>   host      : d3c781782424
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 25554)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================

**Comment by manqizhou** [comment]
I got the same error. The error "ValueError: Number of classes, 37, does not match size of target_names, 38. Try specifying the labels parameter" means the number of predicted class and target class is different. I replace the `print(classification_report(truths, predictions, target_names=label_dict.tolist(), digits=4))` with `print(classification_report(truths, predictions, **labels=np.arange(0,len(label_dict.tolist()),1)**,target_names=label_dict.tolist(), digits=4))` and it solved my issue.

**Comment by TencentAILabHealthcare** [comment]
It seems that the number of predicted classes and target classes is different. One possible reason is that our method uses the UNASSIGN_THRES parameters to determine whether the cell likely belongs to a novel class that didn't appear in the training set. You can check the names of predicted classes and the names of target classes in your codes for further troubleshooting.
