### ISSUE TITLE
About pretraining process

### ISSUE THREAD

**Issue by QiaolinLu** [TencentAILabHealthcare/scBERT#23]
Hi, I am trying to reproduce the pretraining process, and I want to know the pretraining resources,  about the number of GPUs and pretraining time. Thanks

**Comment by TencentAILabHealthcare** [comment]
Hi, the pre-training process takes about 32 GPUs and 1-2 week in a distributed manner.

**Comment by QiaolinLu** [comment]
Hi, which kind of GPU, and How large the memory is?

**Comment by TencentAILabHealthcare** [comment]
You can use V100.

**Comment by QiaolinLu** [comment]
thanks

**Comment by SELECT-FROM** [comment]
> Hi, I am trying to reproduce the pretraining process, and I want to know the pretraining resources, about the number of GPUs and pretraining time. Thanks
Hello, could you please send me a copy of the pre training script
