### ISSUE TITLE
questions in finetune code

### ISSUE THREAD

**Issue by QiaolinLu** [TencentAILabHealthcare/scBERT#24]
Hi, I have a question in fintune.py code, why should we concatenate full_seq with `torch.tensor([0])`
`full_seq = torch.cat((full_seq, torch.tensor([0]))).to(device)`
Thanks

**Comment by QiaolinLu** [comment]
Sorry, not yet. I am also confused that why they use random start in their `__getitem__` function.

**Comment by justSOZ** [comment]
@QiaolinLu 冒犯了，我有个问题是：ModuleNotFoundError: No module named 'fast_transformers'
报错，你是怎么解决的？

GitHub也没有可以联系您的方式，所以出此下策，想问问你。

**Comment by QiaolinLu** [comment]
> @QiaolinLu 冒犯了，我有个问题是：ModuleNotFoundError: No module named 'fast_transformers' 报错，你是怎么解决的？
> 
> GitHub也没有可以联系您的方式，所以出此下策，想问问你。

you might need to install fast_transformers package, try it 

> https://pypi.org/project/fast-transformer/
