### ISSUE TITLE
launch.py: error: unrecognized arguments: --data_path

### ISSUE THREAD

**Issue by AllenShow** [TencentAILabHealthcare/scBERT#26]
Hello,

Thank you for providing the tool.

However, I encountered an error with  the finetune procedure:
_python3 -m torch.distributed.launch --data_path "./data/Zheng68K.h5ad" --model_path "/data/scbert/data/panglao_pretrained.pth" finetune.py_ 

the error is as follows:

usage: launch.py [-h] [--nnodes NNODES] [--node_rank NODE_RANK] [--nproc_per_node NPROC_PER_NODE]
                 [--master_addr MASTER_ADDR] [--master_port MASTER_PORT] [--use_env] [-m] [--no_python]
                 [--logdir LOGDIR]
                 training_script ...
launch.py: error: **unrecognized arguments**: --data_path

--------------

However, when I put the parameters i.e. the data path and model path into the finetune code as the default parameter, the error disappears. And then use _python3 -m torch.distributed.launch finetune.py_ without any parameters to escape the error.

I read some similar cases from others. Some people suggest use torchrun instead of (the deprecated?) torch.distributed.launch. However it needs to upgrade the torch version which is inconsistent with the requirements.txt. I didn't upgrade because I didn't know whether upgrading torch version and using torchrun  may cause other compatibility issues.

So could you please fix the problem?

**Comment by yzhu-bnt** [comment]
same issue, I tried to put the finetune.py in front, and it worked. 
python3 -m torch.distributed.launch finetune.py --data_path "./data/Zheng68K.h5ad" --model_path "/data/scbert/data/panglao_pretrained.pth"

**Comment by TencentAILabHealthcare** [comment]
Thank you for the report, we have fixed this problem in the script.
