### ISSUE TITLE
Which dataset was used to generate the gene2vec_16906.npy file?

### ISSUE THREAD

**Issue by AllenShow** [TencentAILabHealthcare/scBERT#28]
Thanks

**Comment by sdascoli** [comment]
Hi, did you find an answer to this ? :)

**Comment by AllenShow** [comment]
> Hi, did you find an answer to this ? :)

Nope ╮(╯_╰)╭

**Comment by niehu2018** [comment]
Please check their scBERT paper.
This file may be from this source: https://github.com/jingcheng-du/Gene2vec

**Comment by TencentAILabHealthcare** [comment]
Yes, the file is generated based on the gene2vec paper: Du, J. et al. Gene2vec: distributed representation of genes based on co-expression. BMC Genomics 20, 7–15 (2019)..
