### ISSUE TITLE
How to reproduce the pre-training process

### ISSUE THREAD

**Issue by HelloWorldLTY** [TencentAILabHealthcare/scBERT#29]
Hi, I wonder if there are any reference codes we can use for fine-tuning.

Moreover, Can I use my own datasets with 1000 hvgs to perform analysis? I always receive  an error:
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::CUDAError'

**Comment by TencentAILabHealthcare** [comment]
It seems there is an error ocurring during the python script running on GPU. Please customize your codes for your data. Besides, scBERT didn't use feature selection to generate hvg and the input gene number is more than 10000, covering almost all the genes you can detect. Please dive into the introduction and the result of scBERT paper to find the reason why we do not involve hvg or marker gene selection beforehand.
