### ISSUE TITLE
Downloadable link for the pretrained

### ISSUE THREAD

**Issue by Douglas2Code** [TencentAILabHealthcare/scBERT#3]
Hi! Congrats for the great work! In addition to the data, could you please also provide a downloadable link for the pretrained weights? The current link requires an additional verification step to download. Thank you!

**Comment by TencentAILabHealthcare** [comment]
Hi! I'm glad that you enjoy the work. The download link of pretrained weights is provided in the weixin drive. You can log in the wechat and download it. A large number of users have successfully downloaded via this link. All the downloading operations will be proved.

**Comment by Douglas2Code** [comment]
Hi, thank you for sharing the link, I would still suggest provide alternative ways to download the data as WeChat is not an app that researchers from outside of China mainland are familiar with.

**Comment by TencentAILabHealthcare** [comment]
If you are not going to use WeChat, you can give me your e-mail address. I'll try to send it to you via e-mail.

**Comment by BradBalderson** [comment]
Thanks for such cool work! I'd like to second @Douglas2Code, not sure how to download the data (nor have heard of WeChat). 

I'll send an email to follow up, would really appreciate if you could send me the pre-trained model :) 

I've heard this platform is common for sharing pre-trained models: https://huggingface.co/
