### ISSUE TITLE
请问可以提供finetune完后的模型参数吗

### ISSUE THREAD

**Issue by cx994** [TencentAILabHealthcare/scBERT#31]
您好，我想用您的模型进行细胞类型的注释，但是我的gpu资源有限，重新用您提供的checkpoint进行finetune需要一个多礼拜的时间，请问可以提供利用Zheng68k进行finetune之后的模型参数吗

**Comment by cx994** [comment]
@yfzon @TencentAILabHealthcare

**Comment by wmh1203** [comment]
> 您好，我想用您的模型进行细胞类型的注释，但是我的gpu资源有限，重新用您提供的checkpoint进行finetune需要一个多礼拜的时间，请问可以提供利用Zheng68k进行finetune之后的模型参数吗

Hi 请问您跑出来结果了吗😮‍💨，我最近也打算用这个模型，如果您有跑好的checkpoint可以分享一下吗～谢谢

**Comment by TencentAILabHealthcare** [comment]
Zheng68K只是一个样例数据集，展示如何基于某个数据集finetune模型。Zheng68K可能与您所需要进行注释的单细胞数据的细胞类型有所不同，为了取得最优的效果，建议使用您自己的数据集，处理为样例输入，进行finetune。
