### ISSUE TITLE
Code to annotate and plot cells?

### ISSUE THREAD

**Issue by patricks-lab** [TencentAILabHealthcare/scBERT#36]
Thanks a lot for the great work and paper. I was wondering if there is any code to annotate and plot cells from your pretrained model, in a similar way as Figure 2 of your paper (https://www.nature.com/articles/s42256-022-00534-z/figures/2)? 

Thanks a lot in advance!

**Comment by TencentAILabHealthcare** [comment]
Please take a look at those commonly used packages for single-cell data analysis, such as Scanpy. There are a lot of easy-to-use tutorials on its website.
