### ISSUE TITLE
ModuleNotFoundError: No module named 'local_attention'

### ISSUE THREAD

**Issue by yuzhiguo07** [TencentAILabHealthcare/scBERT#37]
It seems that there is a missing file "local_attention.py" in the performer_pytorch folder.

**Comment by yuzhiguo07** [comment]
solved by pip install local-attention

**Comment by justSOZ** [comment]
> It seems that there is a missing file "local_attention.py" in the performer_pytorch folder.
后面又出现了
ModuleNotFoundError: No module named 'fast_transformers'
报错，你是怎么解决的？
