### ISSUE TITLE
where is 'label' and 'label_dict' files？？？？

### ISSUE THREAD

**Issue by zzltly** [TencentAILabHealthcare/scBERT#38]
如题

**Comment by manqizhou** [comment]
You need to fun finetune.py first. finetune.py will generate 'label' and 'label_dict'

**Comment by wenyuhaokikika** [comment]
run `python finetune.py --model_path ./model/panglao_pretrain.pth`
raise Execption
```
Traceback (most recent call last):
  File "/data/wenyuhao/code/someProject/scBERT/finetune.py", line 48, in <module>
    rank = int(os.environ["RANK"])
  File "/data/wenyuhao/anaconda3/envs/scBERT/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```
can you replace `int(os.environ["RANK"])` use `int(os.environ.get("RANK",0))`?事实上我也不知道RANK应该设置为几？

**Comment by TencentAILabHealthcare** [comment]
Yes, it is generated by the finetune.py.
