### ISSUE TITLE
How to get the cell embedding for UMAP?

### ISSUE THREAD

**Issue by JiahaoChow** [TencentAILabHealthcare/scBERT#39]
Thank you for your great work.

However, it seems unclear in the paper about the embedding to draw the UMAP. 
It is the experssion embedding (which is cells * genes * 200 dimensinal) or the average of the experssion embedding(which is cells * 200 dimensional)?
It would be grateful for you to answer the question. Thank you very much!

**Comment by TencentAILabHealthcare** [comment]
@JiahaoChow Yes, we use the average of the expression embedding to draw the UMAP.
