### ISSUE TITLE
How to train a new model?

### ISSUE THREAD

**Issue by SongqiZhou** [TencentAILabHealthcare/scBERT#40]
Hello, I want to use scBERT, but you haven't provided the corresponding code. How can I retrain a new model? Can we only perform finetune?

**Comment by RadiantWu** [comment]
I meet the same issue!  I have sent a email to the author but get no feedback!

**Comment by TencentAILabHealthcare** [comment]
The pre-training script has been released in this github, please refer to https://github.com/TencentAILabHealthcare/scBERT/blob/master/pretrain.py.
