### ISSUE TITLE
Has anyone been able to reproduce the finetune from the paper?

### ISSUE THREAD

**Issue by markddesimone** [TencentAILabHealthcare/scBERT#42]
I ran scBERT finetune to try repro the results from the paper. I had to use:
- `batch_size 2` to fit in memory with the gui
- `torchrun --nproc_per_node=1` to run standalone. The model overfit and early terminated after 26 epochs and about 12 days of processing.
A graph from the data output:
![image](https://github.com/TencentAILabHealthcare/scBERT/assets/5612966/bbf70ec2-1b47-48dc-839e-7f2ad19c1e0c)

Here's my command explicitly defining all the parameters as they appear in finetune.py:
```sh
torchrun --nproc_per_node=1 finetune.py \
--local_rank 0 \
--bin_num 5 \
--gene_num 16906 \
--epoch 100 \
--seed 2021 \
--batch_size 2 \
--learning_rate 0.0001 \
--grad_acc 60 \
--valid_every 1 \
--pos_embed True \
--data_path scBERT/data/Zheng68K.h5ad \
--model_path scBERT/data/panglao_pretrain.pth \
--ckpt_dir ./ckpts/ \
--model_name finetune
```
I'm very interested to hear if anyone has been able to repro the results of the paper. I could shut down my GUI and run batch_size 3 (the default), but given the run time on my RTX2080ti of 12 days to 26 epochs, I'm loathe to start that. Hoping to get some confirmation here that it'd be worthwhile to single task my machine for that long. 

Thanks

**Comment by TencentAILabHealthcare** [comment]
The finetune results have been reproduced by an independent research group and the reusability report has been published on https://www.nature.com/articles/s42256-023-00757-8, please find more details in their reports and experiment settings.
