### ISSUE TITLE
Checkpoint link is not possible to use

### ISSUE THREAD

**Issue by Alea4jacta6est** [TencentAILabHealthcare/scBERT#46]
Hi, could you please upload your model checkpoint to Google Drive? The current link is in Chinese and requires log in to download the model

**Comment by TencentAILabHealthcare** [comment]
Please request by sending an email to fionafyang@tencent.com.

**Comment by xhl-xhl** [comment]
Hi, could you share model checkpoint to Google Drive? @ @Alea4jacta6est

**Comment by Alea4jacta6est** [comment]
The checkpoint and data have been uploaded to the google drive ([https://drive.google.com/file/d/1ZyC2mGxZK1tLdy3sMOmdJERnSuvR9WZ0/view?usp=sharing; ](https://drive.google.com/file/d/1ZyC2mGxZK1tLdy3sMOmdJERnSuvR9WZ0/view?usp=sharing;https://drive.google.com/file/d/1_Pgk_o8AtQtoXr_ZLQx0eJYoSWzjxC8f/view?usp=sharing)https://drive.google.com/file/d/1_Pgk_o8AtQtoXr_ZLQx0eJYoSWzjxC8f/view?usp=sharing). Please try these two links.

Best,
Fan Yang
