### ISSUE TITLE
Request for Access to Gene embedding: gene2vec_16906.npy 

### ISSUE THREAD

**Issue by sindhura-cs** [TencentAILabHealthcare/scBERT#47]
Hello, I am a graduate student currently working on foundational models for biomedical sequences. I would really appreciate if you could provide the gene2vec_16906.npy file that will greatly aid my research efforts. I plan to test scBERT on my own dataset for comparative analysis.

**Comment by TencentAILabHealthcare** [comment]
Please send an e-mail to fionafyang@tencent.com for the request.
