### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by huangyuyao111** [TencentAILabHealthcare/scBERT#5]
您好，我想请问一下scBERT的代码部分
首先我按照您给的github中的链接进行了数据和checkpoint下载
1. preprocess.py中提到的data = sc.read_h5ad('./data/raw_data.h5ad') 中的raw_data.h5ad是指哪一个呢？是panglao_human.h5ad这个吗？
2. finetune.py中的from performer_pytorch_v2 import PerformerLM，您的代码中没有performer_pytorch_v2

**Comment by TencentAILabHealthcare** [comment]
您好
1. 这是指用户自己的数据，就是一般的scRNA-seq数据保存在h5ad格式即可。
2. 更正代码了

**Comment by justSOZ** [comment]
@huangyuyao111 你跑了吗？这个finetune需要跑多久啊？我跑了一两天了，100epoch还没跑完一半
