### ISSUE TITLE
where is gene2vec_16906.npy?

### ISSUE THREAD

**Issue by AprilYuge** [TencentAILabHealthcare/scBERT#9]
Hi,

I am trying to use pretrained scBERT on my data to finetune it, but an error message said No such file or directory: '../data/gene2vec_16906.npy'. Could you provide this file as well?

Best,

Yuge

**Comment by AprilYuge** [comment]
Also, it seems like I need to know the order of genes in your gene2vec emb matrix in order to align genes in my training data with your emb and the pretrained model. Correct me if I am wrong.

**Comment by TencentAILabHealthcare** [comment]
Hi Yuge,
The gene2vec_16906.npy has been provided in the Data section in the readme. Please download via the provided link.
Yes, the users need to align their data with the order of genes used in this model. Unless they would like to modify the gene embedding by themselves.

**Comment by lavanyanemani96** [comment]
Hi can you provide the order of the genes in your gene2vec_16906.npy file?

**Comment by liump2004** [comment]
> Hi Yuge, The gene2vec_16906.npy has been provided in the Data section in the readme. Please download via the provided link. Yes, the users need to align their data with the order of genes used in this model. Unless they would like to modify the gene embedding by themselves.

你好，请问是否使用了preprocess.py之后，数据的gene order就已经match了？

**Comment by cpu-yun** [comment]
> > Hi Yuge, The gene2vec_16906.npy has been provided in the Data section in the readme. Please download via the provided link. Yes, the users need to align their data with the order of genes used in this model. Unless they would like to modify the gene embedding by themselves.
> 
> 你好，请问是否使用了preprocess.py之后，数据的gene order就已经match了？

您好！我也是这个问题，请问您现在了解了吗？
另外就是preprocess.py的panglao_10000.h5ad在哪里可以获取？
